### ISSUE TITLE
骨大，斗胆一问，能贴个烧写文档码？

### ISSUE THREAD

**Issue by JerryRowe** [DHDAXCW/lede-rockchip#13]
已生成
openwrt-rockchip-armv8-firefly_station-p2-ext4-sysupgrade.img.gz
openwrt-rockchip-armv8-firefly_station-p2-squashfs-sysupgrade.img.gz
请问该文件如何烧写到station中？

**Comment by DHDAXCW** [comment]
参考这个 https://github.com/DHDAXCW/DoorNet2/blob/main/emmc.md
顺便丢个rk356x专用rkbin https://github.com/DHDAXCW/DoorNet2/blob/mere/data/MiniLoaderAllrk3568%20.bin

**Comment by JerryRowe** [comment]
参考了原理已经烧写成功。能在咨询一下6.0内核在station p2中如何开启无线支持呢？板载邮票封装ic AP6275S

**Comment by DHDAXCW** [comment]
没加支持。。。等有空firefly过来pr一下

**Comment by JerryRowe** [comment]
5.4支持吗？目前编译5.4出现


lede-rockchip/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.4.193/arch/arm64/boot/dts/rockchip/rk3568-roc-pc.dts:7:10: fatal error: dt-bindings/soc/rockchip,vop2.h: No such file or directory
    7 | #include <dt-bindings/soc/rockchip,vop2.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:82: recipe for target '/home/jerry/lede-rockchip-5.4/lede-rockchip/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-roc-pc.dtb' failed
make[5]: *** [/home/jerry/lede-rockchip-5.4/lede-rockchip/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-roc-pc.dtb] Error 1
make[5]: Leaving directory '/home/jerry/lede-rockchip-5.4/lede-rockchip/target/linux/rockchip/image'
Makefile:25: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/jerry/lede-rockchip-5.4/lede-rockchip/target/linux/rockchip'
Makefile:11: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/jerry/lede-rockchip-5.4/lede-rockchip/target/linux'
time: target/linux/install#11.81#7.03#18.29
    ERROR: target/linux failed to build.
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 1
make[2]: Leaving directory '/home/jerry/lede-rockchip-5.4/lede-rockchip'
target/Makefile:19: recipe for target '/home/jerry/lede-rockchip-5.4/lede-rockchip/staging_dir/target-aarch64_generic_musl/stamp/.target_install' failed
make[1]: *** [/home/jerry/lede-rockchip-5.4/lede-rockchip/staging_dir/target-aarch64_generic_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/jerry/lede-rockchip-5.4/lede-rockchip'
/home/jerry/lede-rockchip-5.4/lede-rockchip/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by DHDAXCW** [comment]
根本不支持~我只给他用6.0

**Comment by JerryRowe** [comment]
哈哈哈哈，一删解千愁，不用porting了。
