### ISSUE TITLE
大哥，H68K没用吗？

### ISSUE THREAD

**Issue by leesonaa** [DHDAXCW/lede-rockchip#15]
直接克隆到本地。make menuconfig后发现没有，又去armv8.mk里去掉注释，然后默认编译。好像过不了。。。
我是小白，肯请大哥指点。

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/lede-rockchip/blob/stable/linux6.x.md

**Comment by leesonaa** [comment]
> 
收到，谢谢大哥指点，我试试看。
