### ISSUE TITLE
R5C，拨不上号

### ISSUE THREAD

**Issue by Matrix-CN** [DHDAXCW/lede-rockchip#16]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
R5C wan口没发拨号
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
无
### (1) 具体问题

A:大佬，昨晚用的你代码编译了r5c，wan口拨不上号。用winscp进/network，把wan口的mac地址改成lan口的Mac 地址，才拨上号

### (2) 路由器型号和固件版本

A：r5c，内核6.1.2

### (3) 详细日志

A：

**Comment by DHDAXCW** [comment]
刚看了代码也没问题呢？

**Comment by Matrix-CN** [comment]
我昨晚刷的，现在在上班，没发贴日志。看恩山上是有人这样解释的，是R2S无法拨号:(个人认为这个情况, 大多数是存在于可以拨号获得公网ip的网络环境, 拨号获得内网ip的也有一定可能.
因为,大量的人刷了同样的固件,导致网口mac地址相同,只要是用来做主路由的, wan口的mac地址就会映射到公网环境.
只要有人和你使用的是同一个固件,同样的网络wan口配置, 那么你就有可能因为mac地址冲突而无法获取ip.
正确方法是更改r2s wan口mac即可, 复制一个本地局域网内的mac地址随便更改两个数字, 写入刀wan口,重启路由器.
本人是这么解决的 , 如有不同见解换用交流指正.)
是R5C没mac芯片导致的吗？有空贴个日志

**Comment by DHDAXCW** [comment]
刚试了拨号，能正常拨号

**Comment by 0x676e67** [comment]
> 我昨晚刷的，现在在上班，没发贴日志。看恩山上是有人这样解释的，是R2S无法拨号:(个人认为这个情况, 大多数是存在于可以拨号获得公网ip的网络环境, 拨号获得内网ip的也有一定可能. 因为,大量的人刷了同样的固件,导致网口mac地址相同,只要是用来做主路由的, wan口的mac地址就会映射到公网环境. 只要有人和你使用的是同一个固件,同样的网络wan口配置, 那么你就有可能因为mac地址冲突而无法获取ip. 正确方法是更改r2s wan口mac即可, 复制一个本地局域网内的mac地址随便更改两个数字, 写入刀wan口,重启路由器. 本人是这么解决的 , 如有不同见解换用交流指正.) 是R5C没mac芯片导致的吗？有空贴个日志

![image](https://user-images.githubusercontent.com/51810656/210692931-6d676a87-f3dd-4ff0-9be4-b95c0a7eb97c.png)
![image](https://user-images.githubusercontent.com/51810656/210692961-40a99363-acf1-404f-b7b6-80f8a35526c6.png)
