### ISSUE TITLE
r5s编译失败了，求助

### ISSUE THREAD

**Issue by fishg** [DHDAXCW/lede-rockchip#18]
make[4]: Entering directory '/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86'
make[5]: Entering directory '/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86/src'
aarch64-openwrt-linux-musl-gcc -O3 -pipe -mtune=cortex-a55 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86=dnsmasq-2.86 -Wformat -Werror=format-security -DPIC -fPIC -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -flto -I/mnt/sdb/code/rk/staging_dir/toolchain-aarch64_cortex-a55_gcc-11.3.0_musl/usr/include -I/mnt/sdb/code/rk/staging_dir/toolchain-aarch64_cortex-a55_gcc-11.3.0_musl/include/fortify -I/mnt/sdb/code/rk/staging_dir/toolchain-aarch64_cortex-a55_gcc-11.3.0_musl/include -DHAVE_UBUS -DHAVE_POLL_H   -DNO_DHCP6  -DNO_AUTH  -DHAVE_CONNTRACK      -DVERSION='"2.86"'      -I/mnt/sdb/code/rk/staging_dir/target-aarch64_cortex-a55_musl/usr/include      -c cache.c
aarch64-openwrt-linux-musl-gcc -O3 -pipe -mtune=cortex-a55 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86=dnsmasq-2.86 -Wformat -Werror=format-security -DPIC -fPIC -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -flto -I/mnt/sdb/code/rk/staging_dir/toolchain-aarch64_cortex-a55_gcc-11.3.0_musl/usr/include -I/mnt/sdb/code/rk/staging_dir/toolchain-aarch64_cortex-a55_gcc-11.3.0_musl/include/fortify -I/mnt/sdb/code/rk/staging_dir/toolchain-aarch64_cortex-a55_gcc-11.3.0_musl/include -DHAVE_UBUS -DHAVE_POLL_H   -DNO_DHCP6  -DNO_AUTH  -DHAVE_CONNTRACK      -DVERSION='"2.86"'      -I/mnt/sdb/code/rk/staging_dir/target-aarch64_cortex-a55_musl/usr/include      -c rfc1035.c
rfc1035.c: In function 'report_addresses':
rfc1035.c:1065:56: error: 'struct dnsmasq_daemon' has no member named 'workspacename'
 1065 |               if (!extract_name(header, len, &p, daemon->workspacename, 1, 0))
      |                                                        ^~
rfc1035.c:1067:66: error: 'struct dnsmasq_daemon' has no member named 'workspacename'
 1067 |               if (safe_name(daemon->namebuff) && safe_name(daemon->workspacename))
      |                                                                  ^~
rfc1035.c:1068:92: error: 'struct dnsmasq_daemon' has no member named 'workspacename'
 1068 |                 ubus_event_bcast_connmark_allowlist_resolved(mark, daemon->namebuff, daemon->workspacename, attl);
      |                                                                                            ^~
make[5]: *** [/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86/Makefile:166: rfc1035.o] Error 1
make[5]: Leaving directory '/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86/src'
make[4]: *** [Makefile:91: all] Error 2
make[4]: Leaving directory '/mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86'
make[3]: *** [Makefile:200: /mnt/sdb/code/rk/build_dir/target-aarch64_cortex-a55_musl/dnsmasq-full/dnsmasq-2.86/.built] Error 2
make[3]: Leaving directory '/mnt/sdb/code/rk/package/network/services/dnsmasq'
time: package/network/services/dnsmasq/full/compile#0.32#0.10#0.39
    ERROR: package/network/services/dnsmasq failed to build (build variant: full).
make[2]: *** [package/Makefile:116: package/network/services/dnsmasq/compile] Error 1
make[2]: Leaving directory '/mnt/sdb/code/rk'
make[1]: *** [package/Makefile:110: /mnt/sdb/code/rk/staging_dir/target-aarch64_cortex-a55_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/sdb/code/rk'
make: *** [/mnt/sdb/code/rk/include/toplevel.mk:231: world] Error 2

**Comment by DHDAXCW** [comment]
重新编译

**Comment by fishg** [comment]
我试试开dnssec
https://github.com/openwrt/openwrt/issues/9043

**Comment by fishg** [comment]
开了dnssec 可以了
