### ISSUE TITLE
3f5c892 在 menuconfig 时没有 Rockchip 选项

### ISSUE THREAD

**Issue by SuWeipeng** [DHDAXCW/lede-rockchip#29]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：r5c，切换到 6.1 内核后 make menuconfig 时没有 Rockchip 选项

### (2) 路由器型号和固件版本

A：NanoPi R5C

### (3) 详细日志

A：

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/lede-rockchip/blob/stable/target/linux/rockchip/image/armv8.mk#L136 把#去掉再menuconfig 
![image](https://user-images.githubusercontent.com/74764072/218398364-f2a45a3c-bd53-4339-93ba-19ec382c2788.png)

**Comment by SuWeipeng** [comment]
https://github.com/DHDAXCW/lede-rockchip/blob/stable/linux6.x.md
在做这个链接所示的操作之前是有的，做完这些操作就没了

**Comment by SuWeipeng** [comment]
没的是 Rockchip 选项，不是在有 Rockchip 的情况下找不到 r5c

**Comment by SuWeipeng** [comment]
> https://github.com/DHDAXCW/lede-rockchip/blob/stable/linux6.x.md 在做这个链接所示的操作之前是有的，做完这些操作就没了

进入 menuconfig 的第一项 "Targe System" 里没有 "Rockchip"

**Comment by DHDAXCW** [comment]
我重新下载源码又试了

![image](https://user-images.githubusercontent.com/74764072/218420105-6d26c277-1fe4-49a4-b6e5-7b3cda70f2fd.png)

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/218420105-6d26c277-1fe4-49a4-b6e5-7b3cda70f2fd.png)

**Comment by SuWeipeng** [comment]
target/linux/rockchip/Makefile

**Comment by SuWeipeng** [comment]
> target/linux/rockchip/Makefile

能看下您这个文件的内容么

**Comment by SuWeipeng** [comment]
我的是
```
KERNEL_PATCHVER=6.1
KERNEL_TESTING_PATCHVER=5.15
```

**Comment by SuWeipeng** [comment]
之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE

**Comment by DHDAXCW** [comment]
```
# SPDX-License-Identifier: GPL-2.0-only

include $(TOPDIR)/rules.mk

BOARD:=rockchip
BOARDNAME:=Rockchip
FEATURES:=ext4 audio usb usbgadget display gpio fpu pci pcie rootfs-part boot-part squashfs
SUBTARGETS:=armv8

KERNEL_PATCHVER=6.1
KERNEL_TESTING_PATCHVER=6.1

define Target/Description
	Build firmware image for Rockchip SoC devices.
endef

include $(INCLUDE_DIR)/target.mk

DEFAULT_PACKAGES += uboot-envtools partx-utils resize2fs e2fsprogs mkf2fs kmod-gpio-button-hotplug kmod-usb-dwc2 kmod-usb3 kmod-usb-dwc3 \
		    automount autocore-arm autosamba fdisk luci-app-cpufreq cfdisk e2fsprogs ethtool haveged htop luci-app-diskman kmod-usb2-pci \
		    wpad-wolfssl libwolfssl-benchmark usb-modeswitch usbutils luci-app-zerotier luci-app-ttyd usb-modeswitch pciutils

KERNELNAME:=Image dtbs

$(eval $(call BuildTarget))
```

**Comment by SuWeipeng** [comment]
还是不行，大佬能发布个 release 的固件么，我买了 2 个 MT7921，在“接口”里都找不到“无线”，好灰心

**Comment by DHDAXCW** [comment]
我也没机器，也没无线网卡，全是靠别人帮我测的。。。去电报群找我

**Comment by 0x676e67** [comment]
> 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE

今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动

**Comment by SuWeipeng** [comment]
> > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> 
> 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动

好的，谢谢大佬指点

**Comment by 0x676e67** [comment]
> > > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> > 
> > 
> > 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动
> 
> 好的，谢谢大佬指点

https://github.com/gngpp/NanoPi-R5C/releases 今天的固件能用了，可以关掉这个issue了

**Comment by SuWeipeng** [comment]
> > > > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> > > 
> > > 
> > > 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动
> > 
> > 
> > 好的，谢谢大佬指点
> 
> https://github.com/gngpp/NanoPi-R5C/releases 今天的固件能用了，可以关掉这个issue了

您的 release 里 192.168.2.1 那版固件无线作为 client 可以扫描出可用的 wifi 列表，新固件能识别网卡，但是扫描不出可用的 wifi 列表（扫完的解果是空的，没有东西）

**Comment by 0x676e67** [comment]
> > > > > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> > > > 
> > > > 
> > > > 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动
> > > 
> > > 
> > > 好的，谢谢大佬指点
> > 
> > 
> > https://github.com/gngpp/NanoPi-R5C/releases 今天的固件能用了，可以关掉这个issue了
> 
> 您的 release 里 192.168.2.1 那版固件无线作为 client 可以扫描出可用的 wifi 列表，新固件能识别网卡，但是扫描不出可用的 wifi 列表（扫完的解果是空的，没有东西）

<img width="719" alt="image" src="https://user-images.githubusercontent.com/51810656/218652164-e1897cd1-fff1-49b4-b96b-5bb0aa86afcd.png">
命令行是可以扫的，驱动锅，上游这样也没办法，192.168.2.1版本是开不了ax模式的。有空我换lede驱动测试一下

**Comment by SuWeipeng** [comment]
> > > > > > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> > > > > 
> > > > > 
> > > > > 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动
> > > > 
> > > > 
> > > > 好的，谢谢大佬指点
> > > 
> > > 
> > > https://github.com/gngpp/NanoPi-R5C/releases 今天的固件能用了，可以关掉这个issue了
> > 
> > 
> > 您的 release 里 192.168.2.1 那版固件无线作为 client 可以扫描出可用的 wifi 列表，新固件能识别网卡，但是扫描不出可用的 wifi 列表（扫完的解果是空的，没有东西）
> 
> <img alt="image" width="719" src="https://user-images.githubusercontent.com/51810656/218652164-e1897cd1-fff1-49b4-b96b-5bb0aa86afcd.png">
> 
> 命令行是可以扫的，驱动锅，上游这样也没办法，192.168.2.1版本是开不了ax模式的。有空我换lede驱动测试一下

我可以用我的 R5C 帮助测试。另外，https://github.com/gngpp/NanoPi-R5C 这个项目打开 issue 可以么，在这个 Repo 下说另一个 Repo 有点跑偏的感觉

**Comment by 0x676e67** [comment]
> > > > > > > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> > > > > > 
> > > > > > 
> > > > > > 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动
> > > > > 
> > > > > 
> > > > > 好的，谢谢大佬指点
> > > > 
> > > > 
> > > > https://github.com/gngpp/NanoPi-R5C/releases 今天的固件能用了，可以关掉这个issue了
> > > 
> > > 
> > > 您的 release 里 192.168.2.1 那版固件无线作为 client 可以扫描出可用的 wifi 列表，新固件能识别网卡，但是扫描不出可用的 wifi 列表（扫完的解果是空的，没有东西）
> > 
> > 
> > <img alt="image" width="719" src="https://user-images.githubusercontent.com/51810656/218652164-e1897cd1-fff1-49b4-b96b-5bb0aa86afcd.png">
> > 命令行是可以扫的，驱动锅，上游这样也没办法，192.168.2.1版本是开不了ax模式的。有空我换lede驱动测试一下
> 
> 我可以用我的 R5C 帮助测试。另外，https://github.com/gngpp/NanoPi-R5C 这个项目打开 issue 可以么，在这个 Repo 下说另一个 Repo 有点跑偏的感觉

可以

**Comment by 0x676e67** [comment]
> > > > > > > 之所以编译，是因为我用 https://github.com/gngpp/NanoPi-R5C/releases 这里的固件，用 MT7921 网卡还是没有“无线”，我的网卡是 MT7921LE
> > > > > > 
> > > > > > 
> > > > > > 今天的固件，action抽风没下到驱动，打不上去，等晚点才更新，前面两个日期版本有驱动
> > > > > 
> > > > > 
> > > > > 好的，谢谢大佬指点
> > > > 
> > > > 
> > > > https://github.com/gngpp/NanoPi-R5C/releases 今天的固件能用了，可以关掉这个issue了
> > > 
> > > 
> > > 您的 release 里 192.168.2.1 那版固件无线作为 client 可以扫描出可用的 wifi 列表，新固件能识别网卡，但是扫描不出可用的 wifi 列表（扫完的解果是空的，没有东西）
> > 
> > 
> > <img alt="image" width="719" src="https://user-images.githubusercontent.com/51810656/218652164-e1897cd1-fff1-49b4-b96b-5bb0aa86afcd.png">
> > 命令行是可以扫的，驱动锅，上游这样也没办法，192.168.2.1版本是开不了ax模式的。有空我换lede驱动测试一下
> 
> 我可以用我的 R5C 帮助测试。另外，https://github.com/gngpp/NanoPi-R5C 这个项目打开 issue 可以么，在这个 Repo 下说另一个 Repo 有点跑偏的感觉

可以
