### ISSUE TITLE
骷髅佬，源码有这个错误如何解决

### ISSUE THREAD

**Issue by xwndo** [DHDAXCW/lede-rockchip#43]
骷髅佬，源码有这个错误如何解决，没有做任何更改，执行./scripts/feeds install -a 就报这个错了
![clipboard_20230630_110136](https://github.com/DHDAXCW/lede-rockchip/assets/44762565/88d9f1d8-c762-44de-8221-6078325a806b)

**Comment by xwndo** [comment]
开始有这个错误直接编译后也成功了，然后在次
./scripts/feeds update -a
./scripts/feeds install -a
就没有这个错误了

**Comment by DHDAXCW** [comment]
正常，不管它

**Comment by xwndo** [comment]
好的
