### ISSUE TITLE
lubancat2n 编译到u-boot出错了

### ISSUE THREAD

**Issue by xhybb** [DHDAXCW/lede-rockchip#49]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
make[4]: Entering directory '/home/bored/lede-rockchip/build_dir/target-aarch64_generic_musl/u-boot-lubancat-2n-rk3568/u-boot-2024.01'

*** pylibfdt does not seem to be available with python3

make[4]: *** [Makefile:2014: scripts_dtc] Error 1

make[4]: Leaving directory '/home/bored/lede-rockchip/build_dir/target-aarch64_generic_musl/u-boot-lubancat-2n-rk3568/u-boot-2024.01'

make[3]: *** [Makefile:265: /home/bored/lede-rockchip/build_dir/target-aarch64_generic_musl/u-boot-lubancat-2n-rk3568/u-boot-2024.01/.built] Error 2

make[3]: Leaving directory '/home/bored/lede-rockchip/package/boot/uboot-rockchip'

time: package/boot/uboot-rockchip/lubancat-2n-rk3568/compile#1.76#0.89#2.81

    ERROR: package/boot/uboot-rockchip failed to build (build variant: lubancat-2n-rk3568).

make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1

make[2]: Leaving directory '/home/bored/lede-rockchip'

make[1]: *** [package/Makefile:110: /home/bored/lede-rockchip/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2

make[1]: Leaving directory '/home/bored/lede-rockchip'

make: *** [/home/bored/lede-rockchip/include/toplevel.mk:231：world] 错误 2

**Comment by DHDAXCW** [comment]
`*** pylibfdt does not seem to be available with python3`
先本机安装`sudo apt-get install swig python-dev python3-dev`再`pip3 install pylibfdt -i https://pypi.tuna.tsinghua.edu.cn/simple`
