### ISSUE TITLE
ERROR: package/kernel/mac80211 failed to build (build variant: regular). mac80211报错

### ISSUE THREAD

**Issue by ghost** [DHDAXCW/lede-rockchip#55]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：编译过程中显示

### (2) 路由器型号和固件版本

A：编译x86和Rockchip均显示mac80211报错

### (3) 详细日志

A：

**Comment by DHDAXCW** [comment]
我今天还特意编译了一下能过，你这都报错？
要不你直接换稳定版就行，切换分支 `patch`
`git clone -m patch https://github.com/DHDAXCW/lede-rockchip`

**Comment by ghost** [comment]
我也是看到今天你修改了这个想试一下，我感觉应该是和我选的东西冲突了，我在再一下
