### ISSUE TITLE
想请教大佬一个问题 R4se加载CONFIG_PACKAGE_kmod-drm-rockchip=y CONFIG_PACKAGE_kmod-drm-panfrost=y报错

### ISSUE THREAD

**Issue by ghost** [DHDAXCW/lede-rockchip#56]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
R4se加载CONFIG_PACKAGE_kmod-drm-rockchip=y CONFIG_PACKAGE_kmod-drm-panfrost=y报错
Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
选择CONFIG_PACKAGE_kmod-drm-rockchip=y CONFIG_PACKAGE_kmod-drm-panfrost=y报错
提示kmod-fb 缺少fb_io_fops.ko依赖项

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：Rockchip R4se

### (3) 详细日志
软件包 kmod-fb 缺少以下库的依赖项：
fb_io_fops.ko
make[3]: *** [modules/video.mk:118: /home/runner/work/LEDE-Action/LEDE-Action/openwrt/bin/targets/rockchip/armv8/packages/kmod-fb_6.6.38-1_aarch64_generic.ipk] Error 1
make[3]: Leaving directory '/home/runner/work/LEDE-Action/LEDE-Action/openwrt/package/kernel/linux'
time: package/kernel/linux/compile#3.11#0.51#3.59
    ERROR: package/kernel/linux failed to build.
A：

**Comment by DHDAXCW** [comment]
再编译一次
