### ISSUE TITLE
 编译Alist报错：

### ISSUE THREAD

**Issue by LIKE2000-ART** [DHDAXCW/lede-rockchip#57]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：https://github.com/sbwml/luci-app-alist 后
使用命令make package/community/luci-app-alist/alist/compile V=s 编译失败

### (2) 路由器型号和固件版本

A：R5c Google Colab编译

### (3) 详细日志

A：
make[2]: Entering directory '/content/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/content/openwrt/scripts/config'
time: target/linux/prereq#0.14#0.10#0.23
Checking 'python3-pyelftools'... ok.
Checking 'python3-dev'... ok.
Checking 'python3-setuptools'... ok.
Checking 'swig'... ok.
make[1]: Entering directory '/content/openwrt'
make[2]: Entering directory '/content/openwrt/customfeeds/packages/lang/golang/golang'
make[2]: Leaving directory '/content/openwrt/customfeeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#1.64#0.64#2.33
make[2]: Entering directory '/content/openwrt/package/libs/toolchain'
touch /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.prepared_5a8484f5382da0ccbab85aca4af8ac82_6664517399ebbbc92a37c5bb081b5c53_check
mkdir -p /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain
touch /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.prepared_5a8484f5382da0ccbab85aca4af8ac82_6664517399ebbbc92a37c5bb081b5c53
rm -f /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.configured_*
rm -f /content/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.toolchain_installed
(cd /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/./; if [ -x ./configure ]; then find /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/ -name config.guess | xargs -r chmod u+w; find /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/ -name config.guess | xargs -r -n1 cp --remove-destination /content/openwrt/scripts/config.guess; find /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/ -name config.sub | xargs -r chmod u+w; find /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/ -name config.sub | xargs -r -n1 cp --remove-destination /content/openwrt/scripts/config.sub; AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/content/openwrt/build_dir/target-aarch64_generic_musl/toolchain=toolchain -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/content/openwrt/build_dir/target-aarch64_generic_musl/toolchain=toolchain -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/content/openwrt/build_dir/target-aarch64_generic_musl/toolchain=toolchain -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/include -I/content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/include/fortify -I/content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/include " LDFLAGS="-L/content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -znow -zrelro "   ./configure --target=aarch64-openwrt-linux --host=aarch64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.built
touch /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.built_check
touch /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.built
rm -rf /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc.installed /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc
mkdir -p /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc
install -d -m0755 /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc/lib /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib/ld-musl-*.so* /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/content/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib/ld-musl-*.so*': No such file or directory
make[2]: *** [Makefile:726: /content/openwrt/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/content/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.17#0.18#0.37
    ERROR: package/libs/toolchain failed to build.
make[1]: *** [package/Makefile:116: package/libs/toolchain/compile] Error 1
make[1]: Leaving directory '/content/openwrt'
make: *** [/content/openwrt/include/toplevel.mk:231: package/community/luci-app-alist/alist/compile] Error 2

**Comment by DHDAXCW** [comment]
```
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang
```

**Comment by LIKE2000-ART** [comment]
> ```
> rm -rf feeds/packages/lang/golang
> git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang
> ```
感谢大佬回复
目前更新golang之后make报错：bash: line 1: aarch64-openwrt-linux-musl-gcc: command not found
