### ISSUE TITLE
make menuconfig 错误

### ISSUE THREAD

**Issue by chaoyanggo** [DHDAXCW/lede-rockchip#60]
## 2. 详细叙述

make menuconfig 提示递归依赖关系！

### (1) 具体问题

Collecting package info: done
tmp/.config-package.in:90843:error: recursive dependency detected!
tmp/.config-package.in:90843:   symbol PACKAGE_baresip-mod-avcodec is selected by PACKAGE_baresip-mod-avformat
tmp/.config-package.in:90871:   symbol PACKAGE_baresip-mod-avformat depends on PACKAGE_baresip-mod-avcodec
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

**Comment by DHDAXCW** [comment]
忘了看，早解决了，等今天推送。。
