### ISSUE TITLE
feeds update -a  Process completed with exit code 1.

### ISSUE THREAD

**Issue by zhangguanzhang** [DHDAXCW/lede-rockchip#9]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

```
 ./scripts/feeds update -a
Updating feed 'packages' from 'https://github.com/DHDAXCW/packages' ...
Cloning into './feeds/packages'...
fatal: No url found for submodule path 'luci' in .gitmodules
failed.
Updating feed 'luci' from 'https://github.com/DHDAXCW/luci' ...
```

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/packages/commit/9cf7e112813901c85b2d5cd7c68d7fc76dba3aae 感谢反馈，已修复，没注意到package里面多了luci软连接。。。感谢这位大佬帮忙的 @xiangfeidexiaohuo 
![image](https://user-images.githubusercontent.com/74764072/196439650-c6627dfe-4c5e-4879-8920-0364db242361.png)
